# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f98e89c349e701f6a36af2f1fec23285227e5cf38b684b7141e4a5ac9b5dc82c4070e18529d1f967b8155e844961cf1a0441eeedf939daf48cf5d2dc8831450

test:
  secret_key_base: 3607d95c007fcae3e7965ddbc9437aae7567c14ef077d3752812699197739780c82352efc051d494778ae8ec4095fb9aa3491a46a8db2f9e82e7e2ffd664e177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
